#!/usr/bin/env python
"""
One-time migration helper: slice the hand-written singleton pages at the repo
root into body / head / script fragments under _templates/pages/, and emit
_data/pages.yaml metadata, so they can be regenerated through the shared
base.html.j2 shell by build_pages() in build.py.

After running this once and committing the fragments, the fragments become the
maintained source of truth — edit a page by editing its *.body.html fragment
and rebuilding. Re-running the extractor would simply re-derive them from the
(now generated) .htm files, so it is not part of the normal build.

Usage:
    python _build/extract_pages.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGES_DIR = ROOT / "_templates" / "pages"

# Pages to migrate (repo-root <key>.htm). Order controls pages.yaml order.
PAGE_KEYS = [
    # building_performance is now a first-class data-driven page (build.py:
    # build_building_performance + _templates/building_performance.html.j2),
    # not a frozen fragment — intentionally not listed here.
    "landlords",
    "tenants",
    "saving_opportunities",
    "swb_overview",
    "system_chw",
    "docs_manuals",
    "meter_manuals",
    "report_template",
]

STD_STYLESHEETS = ("bootstrap", "project/2.0/style.css", "boxicons")
LIVE_POINTS = '<script src="js/project/2.0/live-points.js"></script>'
SIDEBAR_SCRIPT = '<script src="js/project/2.0/sidebar-template.js"></script>'


def extract_one(key: str) -> dict:
    src = (ROOT / f"{key}.htm").read_text(encoding="utf-8")
    head = src[: src.index("</head>")]

    # ── metadata ────────────────────────────────────────────────────────────
    page_title = re.search(r"<title>(.*?)</title>", src, re.S).group(1).strip()

    m_container = re.search(r'<div class="container([^"]*)"(?:\s+style="([^"]*)")?>', src)
    container_class = (m_container.group(1) or "").strip()
    container_style = m_container.group(2)

    m_heading = re.search(r'<div class="title-bar">\s*<h1>(.*?)</h1>', src, re.S)
    heading = m_heading.group(1).strip() if m_heading else ""

    no_optergy = "liveDisplayAndDashboard" not in head

    # ── body (between the title-bar close and the container close) ────────────
    after = src[m_heading.end():]
    after = after[after.index("</div>") + len("</div>"):]  # past title-bar close
    region = after[: after.index("\n            </main>")]
    region = region[: region.rindex("\n                </div>")]  # drop container close
    body = region.strip("\n")

    # ── head extras (non-standard stylesheet links + <style> blocks) ──────────
    extras: list[str] = []
    for m in re.finditer(r'[ ]*<link rel="stylesheet" href="([^"]+)">', head):
        if not any(s in m.group(1) for s in STD_STYLESHEETS):
            extras.append(m.group(0))
    m_style = re.search(r"[ ]*(?:<!--.*?-->\s*)?<style>.*?</style>", head, re.S)
    if m_style:
        extras.append(m_style.group(0))
    extra_styles = "\n".join(extras)

    # ── extra scripts (between live-points and the sidebar loader) ────────────
    # The sidebar loader is preceded by its own comment in the originals (whose
    # exact wording varies — "(NO CORS ISSUES!)" in the legacy pages); base
    # emits a canonical one, so cut before any "<!-- Load sidebar" comment.
    i = src.index(LIVE_POINTS) + len(LIVE_POINTS)
    m_sb = re.search(r"\n[ ]*<!-- Load sidebar", src[i:])
    j = i + m_sb.start() if m_sb else src.index(SIDEBAR_SCRIPT, i)
    extra_scripts = src[i:j].strip("\n").rstrip()

    # ── tail scripts (between the sidebar loader and </body>) ─────────────────
    k = src.index(SIDEBAR_SCRIPT) + len(SIDEBAR_SCRIPT)
    tail_scripts = src[k: src.index("</body>", k)].strip("\n").rstrip()

    return {
        "key": key,
        "page_title": page_title,
        "heading": heading,
        "container_class": container_class,
        "container_style": container_style,
        "no_optergy": no_optergy,
        "body": body,
        "extra_styles": extra_styles,
        "extra_scripts": extra_scripts,
        "tail_scripts": tail_scripts,
    }


def yaml_quote(s: str) -> str:
    """Minimal double-quoted YAML scalar (headings may contain HTML/quotes)."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# ─────────────────────────────────────────────────────────────────────────────",
        "# Singleton / one-off pages rendered through _templates/page.html.j2 + base.",
        "# Body and head/script extras live in _templates/pages/<key>.*.html fragments;",
        "# this file carries only per-page metadata. Generated by _build/extract_pages.py",
        "# then hand-maintained. To edit a page, edit its fragment and rebuild.",
        "# ─────────────────────────────────────────────────────────────────────────────",
        "",
        "pages:",
    ]
    for key in PAGE_KEYS:
        d = extract_one(key)
        # Write fragments (body always; others only when non-empty).
        (PAGES_DIR / f"{key}.body.html").write_text(d["body"], encoding="utf-8")
        for frag, val in (
            ("styles", d["extra_styles"]),
            ("extra_scripts", d["extra_scripts"]),
            ("tail_scripts", d["tail_scripts"]),
        ):
            path = PAGES_DIR / f"{key}.{frag}.html"
            if val:
                path.write_text(val, encoding="utf-8")
            elif path.exists():
                path.unlink()

        lines.append(f"  - key: {key}")
        lines.append(f"    out: {key}.htm")
        lines.append(f"    page_title: {yaml_quote(d['page_title'])}")
        lines.append(f"    heading: {yaml_quote(d['heading'])}")
        if d["container_class"]:
            lines.append(f"    container_class: {yaml_quote(d['container_class'])}")
        if d["container_style"]:
            lines.append(f"    container_style: {yaml_quote(d['container_style'])}")
        if d["no_optergy"]:
            lines.append("    no_optergy: true")
        print(
            f"  {key}: body={len(d['body'])}b "
            f"styles={'y' if d['extra_styles'] else '-'} "
            f"extra_scripts={'y' if d['extra_scripts'] else '-'} "
            f"tail={'y' if d['tail_scripts'] else '-'} "
            f"no_optergy={'y' if d['no_optergy'] else '-'}"
        )

    (ROOT / "_data" / "pages.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote _data/pages.yaml ({len(PAGE_KEYS)} pages) and fragments to {PAGES_DIR.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
